spring.application.name=campaigntracker

spring.datasource.url=jdbc:postgresql://localhost:5432/campaigntracker
spring.datasource.username=ahm
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false